#' Heterogeneity Evaluation
#'
#' Evaluating the overall and individually heterogeneity and reproducibility
#' for the given individuals(units) shared in different replicates.
#'
#' @param data A dataset which is constructed by pairs of coefficient
#' values \eqn{ \beta } and standard errors \eqn{ se(\beta)}.
#' @param use_cefn A boolean, denoting whether to use CEFN prior. If the value is TRUE,
#' CEFN prior is used, else, META prior is applied. The default value is TRUE.
#' @param rep A vector, denoting all the \eqn{k^2} (under CEFN prior) or \eqn{r} (under META prior) values constructing the reproducible signals. If not specified,
#' the default one is c(0.105,0.260,0.369), which corresponds to the several prior values satisfy that
#' \eqn{Pr(\beta_{i,1}, \beta_{i,2} have a same sign)=0.99, 0.975, 0.95.}
#' @param irre  A vector, denoting all the \eqn{k^2} or \eqn{r} values constructing the irreproducible signals.If not specified,
#' the default one is c(2.198, 3.636, 6.735), which corresponds to the several prior values satisfy that
#' \eqn{Pr(\beta_{i,1}, \beta_{i,2} have a same sign)=0.75, 0.70, 0.65.}
#' @param oa A vector, denoting all the \eqn{\omega} values to be set on the grid. If not specified, \eqn{\omega} grid will
#' be generated by a dynamic procedure, which is determined by the data structure, namely,
#' \eqn{min(\omega)=min(se(\beta)/2)}, \eqn{max(\omega)=max(\sqrt{\beta^2-se(\beta)^2})}.
#' @param sq_em_tol A small, positive scalar that determines when iterations should be terminated in squarem algorithm.
#' The default value is \eqn{1e-4}.
#' @param fdr.level The user-defined rejection level for false discovery rate.
#'
#' @return
#'
#' A list with the following components:
#' \item{gridweight}{ The final optimal weight vector evaluated on each grid point.}
#' \item{ind_prob}{ A matrix denoting the converged probability for each individual being inside the
#' three different groups, namely, the null, the reproducible and the irreproducible group.}
#' \item{est_prop}{ The estimated proportion value for the three different groups, namely, the null,
#' the reproducible and the irreproducible group.}
#' \item{lfdr}{ The local false discovery rate based on the null hyppthesis of
#' unit belonging to \eqn{H_R}, reproducible group. \eqn{lfdr=1-Pr(H_R)}}
#' \item{significant}{ If fdr.level is specified, a significant object recording
#' True or False will be returned }
#' @importFrom SQUAREM fpiter
#'
#' @importFrom stats runif
#' @importFrom rlist list.append
#' @export
#'
#' @examples
#' data("heterodata")
#' hetero.out<-hetero(heterodata,fdr.level=0.05)
#' names(hetero.out)
#' print(hetero.out$est_prop)
#'

hetero<-function(data,use_cefn=TRUE,rep=NULL,irre=NULL,oa=NULL,
                 sq_em_tol=1e-4,fdr.level=NULL){

  ## Hyperparameter Grid set up
  ### omega set up
  if (is.null(oa)){
    minoa<-median(data[,2])
    maxoa<-quantile(abs(data[,1]),0.90)
    oalist<-minoa
    med<-minoa*sqrt(2)

    while (med<maxoa){
      oalist<-c(oalist,med)
      med<-med*sqrt(2)
    }
    oa<-oalist^2
  }
  ### CEFN prior
  if (use_cefn){
    if (is.null(rep)) {
      rep<-c(0.105,0.260,0.369)
    }
    if (is.null(irre)){
      irre<-c(2.198,3.636,6.735)
    }

    kk<-c(rep,irre)
    hyperparam<-expand.grid(k=kk,oa=oa)

    #### Grid for overall large effect
    for (i in 1:length(kk)){
      oaexp<-max(abs(data[,1]))^2/(kk[i]+1)
      expan<-c(kk[i],oaexp)
      hyperparam<-rbind(hyperparam,expan)
    }
  }
  ### META prior
  else{
    if (is.null(rep)) {
      rep=c(0,6e-3,0.024)
    }
    if (is.null(irre)){
      irre<-c(0.500,0.655,0.795)
    }
    r<-c(rep,irre)
    #### Compute k values
    hyperparam<-c()
    for (i in 1:length(r)){
      kk<-oa*r[i]/(1-r[i])
      param<-cbind(kk,oa)
      hyperparam<-rbind(hyperparam,param)
    }
    #### Grid for overall large effect
    for (i in 1:length(r)){
      kkexp<-max(abs(data[,1]))^2*r[i]
      oaexp<-max(abs(data[,1]))^2*(1-r[i])
      expan<-c(kkexp,oaexp)
      hyperparam<-rbind(hyperparam,expan)
    }
  }

  ### Bayes Factor Calculation
  if (use_cefn){
    bf<-bf.cal.cefn(data,hyperparam)
  }
  else{
    bf<-bf.cal.meta(data,hyperparam)
  }

  ### EM Procedure
  #### Package SQUAREM is used
  K<-nrow(hyperparam)+1
  n<-nrow(data)

  w0<-runif(K)
  w0<-w0/sum(w0)

  bf.result<-fpiter(w0,bf,fixptfn=bf.em,objfn=bf.loglik,control=list(tol=sq_em_tol))

  wfinal<-bf.result$par

  ### gridweight
  gridweight<-cbind(rbind(c(0,0),hyperparam),wfinal)
  rval<-hyperparam[,1]/(hyperparam[,1]+hyperparam[,2])

  hetero.res<-list(3)
  hetero.res[[1]]<-gridweight

  cutoff<-rep[length(rep)]
  eifinal<-matrix(NA,n,K)
  catfinal<-matrix(NA,n,3)
  portion<-rep(NA,3)

  if (use_cefn){
    ### Individual level probability
    for (i in 1:n){
      eifinal[i,]<-exp(log(wfinal)+bf[((i-1)*K+1):(i*K)]-bf.weighted_sum(wfinal,bf,i))
      catfinal[i,1]<-eifinal[i,1] #null
      #reproducible
      catfinal[i,2]<-sum(eifinal[i,which(gridweight[,1]<=cutoff)])-eifinal[i,1]
      #irreproducible
      catfinal[i,3]<-sum(eifinal[i,which(gridweight[,1]>cutoff)])
    }

  }
  else{
    for (i in 1:n){
      eifinal[i,]<-exp(log(wfinal)+bf[((i-1)*K+1):(i*K)]-bf.weighted_sum(wfinal,bf,i))
      catfinal[i,1]<-eifinal[i,1] #null
      #reproducible
      catfinal[i,2]<-sum(eifinal[i,which(rval<=cutoff)])-eifinal[i,1]
      #irreproducible
      catfinal[i,3]<-sum(eifinal[i,which(rval>cutoff)])
    }
  }
  hetero.res[[2]]<-catfinal

  if (use_cefn){
    ### Overall proportion
    portion[1]<-gridweight[1,3]#null
    #reproducible
    portion[2]<-sum(gridweight[which(gridweight[,1]<=cutoff),3])-gridweight[1,3]
    #irreproducible
    portion[3]<-sum(gridweight[which(gridweight[,1]>cutoff),3])
  }
  else{
    portion[1]<-gridweight[1,3]#null
    #reproducible
    portion[2]<-sum(gridweight[which(r<=cutoff),3])-gridweight[1,3]
    #irreproducible
    portion[3]<-sum(gridweight[which(r>cutoff),3])
  }
  hetero.res[[3]]<-portion

  rej_dec<-hetero.lfdr(catfinal,fdr.level)

  if (is.null(fdr.level)){
    hetero.res<-list.append(hetero.res,rej_dec)
    names(hetero.res)<-c("gridweight","ind_prob","est_prop","lfdr")
  }
  else{
    hetero.res<-list.append(hetero.res,rej_dec[[1]],rej_dec[[2]])
    names(hetero.res)<-c("gridweight","ind_prob","est_prop","lfdr","significant")
  }

  return(hetero.res)
}
